const EVENTS = {
  GAME_START: 'GAME_START',
  GAME_OVER: 'GAME_OVER',
  GAME_RESTART: 'GAME_RESTART',

  GAME_INTRO_START: 'GAME_INTRO_START',
  GAME_INTRO_COMPLETE: 'GAME_INTRO_COMPLETE',

  PLAYER_ACTION: 'PLAYER_ACTION',

  ACHIEVEMENT: 'ACHIEVEMENT',
  HIGH_SCORE_UPDATE: 'HIGH_SCORE_UPDATE',

  // Async score management
  HIGH_SCORE_FETCH: {
    REQUEST: 'HIGH_SCORE_FETCH_REQUEST',
    SUCCESS: 'HIGH_SCORE_FETCH_SUCCESS',
    FAIL: 'HIGH_SCORE_FETCH_FAIL',
  },
  HIGH_SCORE_SAVE: {
    REQUEST: 'HIGH_SCORE_SAVE_REQUEST',
    SUCCESS: 'HIGH_SCORE_SAVE_SUCCESS',
    FAIL: 'HIGH_SCORE_SAVE_FAIL',
  },

   // Blockchain-specific events
   BLOCKCHAIN: {
    GAME_START: 'BLOCKCHAIN_GAME_START',
    GAME_END: 'BLOCKCHAIN_GAME_END',
    JUMP_RECORDED: 'BLOCKCHAIN_JUMP_RECORDED',
    TRANSACTION_UPDATED: 'BLOCKCHAIN_TRANSACTION_UPDATED',
    CONNECTION_CHANGED: 'BLOCKCHAIN_CONNECTION_CHANGED',
    ERROR: 'BLOCKCHAIN_ERROR',
    SERVER_CONNECTED: 'BLOCKCHAIN_SERVER_CONNECTED',
    SERVER_DISCONNECTED: 'BLOCKCHAIN_SERVER_DISCONNECTED'
  }
};

export default EVENTS;
